name: Deploy to SAP BTP

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'test'
        type: choice
        options: [test, production]
      confirm:
        description: 'Type "deploy" to confirm'
        required: true
        type: string

jobs:
  deploy:
    if: ${{ inputs.confirm == 'deploy' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Deploy to BTP
      uses: SAP/cloud-sdk-action@v1
      with:
        cloudFoundryApiEndpoint: https://api.cf.${{ secrets.CF_REGION }}.hana.ondemand.com
        cloudFoundrySpace: ${{ secrets.CF_SPACE_${{ inputs.environment }} }}
        cloudFoundryOrg: ${{ secrets.CF_ORG }}
        cloudFoundryUsername: ${{ secrets.CF_USERNAME }}
        cloudFoundryPassword: ${{ secrets.CF_PASSWORD }}
        deployCommand: deploy -f