name: Deploy to SAP BTP

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Use Node.js 20 (required by CDS 9.x)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'

    # Install dependencies including CDS
    - name: Install dependencies
      run: npm ci

    # Build using local CDS installation
    - name: Build project
      run: npx cds build

    # Install Cloud Foundry CLI
    - name: Install Cloud Foundry CLI
      run: |
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get update
        sudo apt-get install cf8-cli -y

    # Deploy to BTP
    - name: Deploy to SAP BTP
      env:
        CF_API: ${{ secrets.CF_API }}
        CF_ORG: ${{ secrets.CF_ORG }}
        CF_SPACE: ${{ secrets.CF_SPACE }}
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      run: |
        cf login -a $CF_API -u "$CF_USERNAME" -p "$CF_PASSWORD" -o $CF_ORG -s $CF_SPACE
        cf create-service-push